# Generated by Django 3.0.8 on 2020-08-07 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20200807_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
