# Generated by Django 3.0.8 on 2020-08-10 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20200807_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actions',
            old_name='wasLiked',
            new_name='liked',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='timeStamp',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='post',
            name='liked',
        ),
        migrations.AddField(
            model_name='actions',
            name='actionUserID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='action_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
