# Generated by Django 3.0.8 on 2020-08-07 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_actions_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actions',
            old_name='liked',
            new_name='wasLiked',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='likes',
            new_name='liked',
        ),
        migrations.AlterField(
            model_name='actions',
            name='postID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.Post'),
        ),
    ]
