# Generated by Django 3.0.8 on 2020-08-18 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20200811_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actions',
            name='saved',
        ),
        migrations.RemoveField(
            model_name='actions',
            name='shared',
        ),
    ]
